# Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Crafter Deployer Upgrade Manager Configuration

pipelines:
  target:
    requires: '>=1.7'
    versions:
      - currentVersion: 1.7
        nextVersion: 2.0
        operations:
          - type: processorUpgrader
            processor: '.+IndexingProcessor'
            add:
              - property: excludeFiles
                values:
                  - '^/sources/.*$'
      - currentVersion: 2.0
        nextVersion: 2.1
        operations:
          - type: addProcessorUpgrader
            envPattern: authoring
            processor: httpMethodCallProcessor
            properties:
              - property: includeFiles
                values: [ "^/?config/studio/plugins/classes/.*$" ]
              - property: method
                value: GET
              - property: url
                value: ${target.studioUrl}/api/2/plugin/script/reload.json?siteId=${target.siteName}&token=${target.studioManagementToken}
            beforeProcessor: fileOutputProcessor
      - currentVersion: 2.1
        nextVersion: 2.2
        operations:
          - type: replaceProcessorUpgrader
            envPattern: (preview|default)
            processor: searchIndexingProcessor
            newProcessor: elasticsearchIndexingProcessor
          - type: removePropertyUpgrader
            envPattern: (preview|default)
            property: target.crafterSearchEnabled
