# Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Crafter Deployer Upgrade Manager Configuration

pipelines:
  target:
    - currentVersion: 1.0
      nextVersion: 1.1
      operations:
        - type: processorUpgrader
          processor: httpMethodCallProcessor
          replace:
            - property: url
              pattern: '^((?!.*&token=).*)$'
              expression: '$1&token=\${target.engineManagementToken}'
    - currentVersion: 1.1
      nextVersion: 1.2
      operations:
        - type: elasticsearchIndexUpgrader
    - currentVersion: 1.2
      nextVersion: 1.3
      operations:
        - type: replaceProcessorUpgrader
          processor: s3SyncProcessor
          conditions:
            includeFiles: '\[\^/\?deployment\-events\\.properties\$\]'
          newProcessor: s3DeploymentEventsProcessor
          deleteProperties:
            - includeFiles
    - currentVersion: 1.3
      nextVersion: 1.4
      operations:
        - type: encryptionUpgrader
    - currentVersion: 1.4
      nextVersion: 1.5
      operations:
        - type: addLifecycleHookUpgrader
          processor: gitPullProcessor
          hookType: delete
          hookName: deleteLocalRepoFolderLifecycleHook
    - currentVersion: 1.5
      nextVersion: 1.6
      operations:
        - type: processorUpgrader
          processor: fileBasedDeploymentEventProcessor
          remove:
            - property: excludeFiles
              pattern: '\[\^/static\-assets/\.\*\$]'
    - currentVersion: 1.6
      nextVersion: 1.7
      operations:
        - type: processorUpgrader
          processor: '.+IndexingProcessor'
          add:
            - property: excludeFiles
              values:
                - '^/sources/.*$'