version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.x
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "n6fuJs+P+y4I9lk1Up1uHLs9qwmm7qDQfMwHiXULJzWrquFntlLLy13pkqccwvxy9jzwgZowjmIfHhlreA3hcHbToh0GfY83Lvg18rlZmHnMklh+5sUnDxzZmN5CkMy0WE/UbDqbs2rZGmdjF6xS5htBUapfftozJnqmr40W69Fp8WZFzYzL4jPhW2RED1ndj26ZT4O2Acoet6zbD1BcYHL/79P8Kb+dHYvkUVmtE6xb4wQbJv7UkJ67sOPBHYf0XapC1riAVKK1Ms869DGqeoGbQvtYLBXCeM1ELadirqpQyxpWJuJDfwU7c08pHbB8rt5HAYjkU6YdKwQyDnlwpqR1OqL8PQmzMkU3SJl84vKcRD6EWtcyn8KkglZBMBmmsYwc/BQBWRNR0duoTdhGn4o+ouPHJ3YRh+mimMLRnu0g+iHwyXROIskwTHPoZf9gO8yJb0lp5l4D+AFenlN6laI14aHsYI3iUrh2JZCuUDekYeaMlzGtEdnuoMS3vu1F9XtxRTkUSPULMFELyfKdDZqpZ7d6HA8tDk7hPVBR3KIbJGLSk9yBkOs2fX5O1LKbDltj0RgZgu1gZdB8S0JsiOqdTcHcm64iKlWDJAqDhmvM7Y8yAbX+QqXbNPHCKEyi1xv8nJuSkz/wDBDv4oKN2TAYiUz7YKa0QI3mvsBsmDE="
        - secure: "kU/nL8yWy1iLjkSL/b87GLq1FbPr4d6pue5G3MJ2P+O7vesltRS9WcY+xsD4pF0IKPPn0bBsIR138grO19gfRANSYWYEhS4+o7vDKGimeQRj9eQN3T2oKRtxbvPgdUZpTT4TfIft13s6P2Lz210PR+LaE3zJteE4ggdIyIUWGVR5XbC82xjmQbV50S9TCd4Yqdbjw8jMb/l/W4mluzSJpHJQUsgkzN8/nfzaw4KGhO/XjI6RcWQbnlbRhkfJZTRt/hQs5cu+veHgCVzA68YPmgd5sdAIohDFsF9tEf/SzdulHzpSLRU6pkScEZV3+GENxPhflbuyvAisoLHAusFWvSFPbCwgCAHgoB5oxJLFDMw6l9nJu7JDTy35aWz7Y4ulfirZXasp4NLTDdiVAqq9GjeIq0IrDikhE077TEtmNmZTTGu46vxoveSYxItiqLUeI0u0k+2ZSz1rjdoA43Bmkl6rvXwQQN4gB8bsuUJFymSNP0MmyILPLXfFHJNnzv3l2/aS0E9CJiUbt/3BAPtIuXBZHbWPRFNnUz7UVjnMHXWl/o/bK2vlKv6B9YUzsrLhBcLhtV0cZ5ir8/u+2sTzfZVV6P3YOHqiBgsYasPrEFIZ2V7a1oyNvgOqNlAWTOXtjy112wlrW6Uq+iLOcwjjlAiidRoalR/nesidDWP4/TY="
