version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk21
branches:
  only:
    - develop
    - support/4.x
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "EwNWugIbnesT2zy7KNaKBrvgRpI86Lr7EwTUBW8yWyZbspAWSq027Bzb01ceeWJIF8NpKKwIBhwGx/ElbEAzYOswu/Rf/SmV0M42esl51edD6IG3UHY5LFiYEhx4JN9s5hpGqPRgCUyWjPUEZ78t4JiP/xxn+31vMU1LxLWnIzD2KFWmfDXuxXe9/RQ9fc0y59xTZ0eeHzxcKFdVVgbjU8qTtz4/xymV5e4wt5I4+7VmPRU6mEJnJLAOMda0hzdHkd0IkP/k4YBqQu0iWgQWR9XNvz0lKjNuynzyTuPWRVSVb3poW4hBI5G6O0zgL7HfFgcmIbsQgkBIBe4F4bsWWtdd0DZJjTczuOXJtpfMoOoI7MA+U4sndP9qqPmAQQsD1x5H1HwXJ8eL6oPVweyM3XZovQguD/0+iOePYXNussFiZNcc16Np7JBKAs42nMPqkrXRkeaV5tAt9jtwDNOBrjwGzy8d0dFvRfzGfM+uHfYM9mXfMOQD/3zSHJWmZ2uqs7+UcE0XznpVH6JuI5LjCEYmuIZ5PBabzyGUIH4xB5fD1145OBzGLBPnq6+RqJeFX55tcwP0yqfUwFH6oL50ymnPlcK0JZq1R4rSUWmxp45j872psiOjDiwAYpjsIud+Bs3DpSrJ1PtTxRW0Zs0aEx81TZCmEkUgz78X4soHsiw="
    - secure: "ChGRacWjXT8p5XHI3kypSba2/iML41J3no0PQyJc2XGUPU3O06Fb882Rod9K+1TZzXEvQeySVoY93WZEpcDXCiUzunh6try1f/GVafpbCJSaod1dLCp7POZUkVR3M4WR0u5qpB1ZcfZZ1QDCYpDPN+RZhGEEtl7nnoIiUnp9VK+EghfQQNCI1YffONJbgW2iAaur728F226kyDpu4xmoR6g67YfwpmO9jH9A2xk07MCP1X3lKuTJFuYi27r0vM5JJGjItPWwLXvHP6OU0QdARyP5ShnVBjfm3XBys7ePVn7SNr+TgwrBLbHmsu9BwT/lH7XOC2hTho+8DfdxWHheRQi6oGu5YoqjL8pNxmQi5MlGOZcF/kI7PuHwWGFXQcRfeLSZGnQrEni2vWCmxYP5o8ANI0HBw/vbouXtd4kCI0Od5iUfrFl2FvOnyG4NTgcQ5v7GN1ouTl15qMuJBALPeB6EZNcyIMDAOhvvSjGjJfc04F4CvZV5nh9G4ojQ68O5Fwbzfbnqg3E4fmu/Uxs1LsXNZ99+ZT2G/SZ0o1Dgw3FUVlHZhAfPxu52DZfjaMIJjl05wxKKfXhAwyOGh7pRz4Vmwrtn/hOFtjtytFc7IKfDjQVFi6Gu7RQw1jg7V7FL7Dv+0tR7piZAGg3ann76dBx5kIvuUTnVq6MaBruFGls="
